# export SESSION_TYPE=redis
export SESSION_PERMANENT=False
export SESSION_USE_SIGNER=True
export SESSION_REDIS=redis://redis:6379

# export CACHE_TYPE=redis
export CACHE_REDIS_HOST=redis
export CACHE_REDIS_PORT=6379
export CACHE_REDIS_DB=0
export CACHE_REDIS_URL=redis://redis:6379
export CACHE_DEFAULT_TIMEOUT=30

export SECRET_KEY=temporarypassword123

export FLASK_APP=app.py
export FLASK_DEBUG=1

run: 
	flask run