version: "3"

services:
  web:
    container_name: web
    image: ifpb/php:8.2-apache-pdo
    build: .
    networks:
      - app-tier
    ports:
      - 1001:80
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-tier
    ports:
      - 1002:3306
    volumes:
      - ./query.sql:/docker-entrypoint-initdb.d/query.sql

networks:
  app-tier:
    driver: bridge
